### ISSUE TITLE
Enable Hide and Show Password feature

### ISSUE THREAD

**Issue by rohit32999** [rohit32999/Netflix-Sign-In-Page#1]

**Comment by rko0211** [comment]
Hello, Please kindly assign me this task under apertre24 . I want to contribute in this issue.

**Comment by YooAshu** [comment]
i want to work on this issue

**Comment by AnitSarkar123** [comment]
Also, Assign me under Apertre'24

**Comment by Debaditya-Som** [comment]
> Hello, Please kindly assign me this task under apertre24 . I want to contribute in this issue.

Here you go @rko0211 , but make sure you give a pr to test branch and not the main branch

**Comment by cjstyles6** [comment]
@rohit32999 can i work on this issue

**Comment by Debaditya-Som** [comment]
> @rohit32999 can i work on this issue

It has been assigned to @rko0211 and the PR has already been merged
