### ISSUE TITLE
Feature: "New to Netflix? Sign up now " is to be left aligned.

### ISSUE THREAD

**Issue by Aniketpatra007** [rohit32999/Netflix-Sign-In-Page#13]
"New to Netflix? Sign up now " is to be left aligned.

**Comment by Debaditya-Som** [comment]
Here you go @Aniketpatra007 , just keep in mind you need to submit this PR within 24hrs as it is an easy issue and submit the issue to the test branch

**Comment by Debaditya-Som** [comment]
Hi @Aniketpatra007, how are you progressing with this issue?

**Comment by Debaditya-Som** [comment]
> Hi @Aniketpatra007, how are you progressing with this issue?

@Aniketpatra007 you haven't responded nor have given any PR so I'm closing this issue
