### ISSUE TITLE
google reCaptcha text is missing

### ISSUE THREAD

**Issue by C0D3K0NG** [rohit32999/Netflix-Sign-In-Page#14]
Goggle reCAPTCHA is missing below new to netflix.

**Comment by Debaditya-Som** [comment]
Do you want to work on this issue?

**Comment by C0D3K0NG** [comment]
Yupp i can do it

**Comment by Debaditya-Som** [comment]
> Yupp i can do it

Here yo go @C0D3K0NG

**Comment by aniketde1112** [comment]
pls assign me this
