### ISSUE TITLE
changing ui for mobile page because netflix has different ui  of sign in page for mobile views

### ISSUE THREAD

**Issue by YooAshu** [rohit32999/Netflix-Sign-In-Page#18]
![Screenshot (53)](https://github.com/rohit32999/Netflix-Sign-In-Page/assets/95643200/49527687-726b-4ec5-8aa7-7ddf0d20af25)

**Comment by Debaditya-Som** [comment]
Here you go @YooAshu  , submit the PR within 3 days and into the test branch. Remember to sync the branch before giving the PR

**Comment by Debaditya-Som** [comment]
Hi @YooAshu how are you progressing with the issue

**Comment by YooAshu** [comment]
Yeah , sorry for the delay I will make PR today

**Comment by Debaditya-Som** [comment]
> Yeah , sorry for the delay I will make PR today

no issues, just sync the fork before giving the pr to avoid the merge conflict
