### ISSUE TITLE
Sign up Page

### ISSUE THREAD

**Issue by rohit32999** [rohit32999/Netflix-Sign-In-Page#2]
Create a Sign up page for new users, that links with the Log In page.

**Comment by rko0211** [comment]
Hello @rohit32999 i want to contribute in this project under Apertre24 kindly assign me this issue. Thank you

**Comment by itsneha15** [comment]
heyy ! Can u pls assign me this task ? I'll fix it . Thanks :)

**Comment by YooAshu** [comment]
i want to work on this issue , pls assign this to me

**Comment by AnitSarkar123** [comment]
Also please ,Assign me under Apertre'24

**Comment by Debaditya-Som** [comment]
> Hello @rohit32999 i want to contribute in this project under Apertre24 kindly assign me this issue. Thank you

We'll start assigning issues from tonight midnight

**Comment by Debaditya-Som** [comment]
> heyy ! Can u pls assign me this task ? I'll fix it . Thanks :)

Here you go @nsrs-78, make sure to sync your branch before submitting the PR into the test branch and also create a link between the sign in and sign up page

**Comment by Debaditya-Som** [comment]
Hi @nsrs-78 how are you progressing with the issue?

**Comment by itsneha15** [comment]
yup , I,ll be doing it shortly

**Comment by itsneha15** [comment]
is this the same as that of landing page ?  Like this one 


![Screenshot 2024-01-05 224825](https://github.com/rohit32999/Netflix-Sign-In-Page/assets/137761848/a0ea9a7c-3d29-4a3d-ab31-9497f3b35892)

**Comment by itsneha15** [comment]
@Debaditya-Som  can u check it once ... Then I'll work on it.

**Comment by Debaditya-Som** [comment]
> @Debaditya-Som can u check it once ... Then I'll work on it.

Yup its alright you can carry on

**Comment by Sneha123-zudo** [comment]
Please assign me this issue

**Comment by rko0211** [comment]
Please assign me this task, i want to make it

**Comment by rko0211** [comment]
Please assign me this task.

**Comment by Debaditya-Som** [comment]
@Sneha123-zudo how are you progressing with this issue?

**Comment by Sneha123-zudo** [comment]
I'm working on it
