### ISSUE TITLE
Changing of the font size and style of "Sign in"

### ISSUE THREAD

**Issue by magnum7701** [rohit32999/Netflix-Sign-In-Page#20]
to change the font style and size of the "Sign in",  "email", "passoword" etc. texts as they do not match with that of the actual Netflix sign in page.

**Comment by Debaditya-Som** [comment]
Here you go @magnum7701, try to submit the PR within 24hrs and into the test branch. Sync the branch in order to avoid merge conflict

**Comment by Debaditya-Som** [comment]
@magnum7701 how are you progressing with this issue?

**Comment by magnum7701** [comment]
@Debaditya-Som i am not able to push my code, its showing certain errrors. i have DMed the details to your discord

**Comment by Debaditya-Som** [comment]
> @Debaditya-Som i am not able to push my code, its showing certain errrors. i have DMed the details to your discord

okay i'm checking it
