### ISSUE TITLE
Adding zoom in and out effect to the words like email and password

### ISSUE THREAD

**Issue by AnkushFTS** [rohit32999/Netflix-Sign-In-Page#21]
![image_2024-01-03_194827827](https://github.com/rohit32999/Netflix-Sign-In-Page/assets/147180674/2883128a-89c1-4a26-a7c9-c21dc1653725)

**Comment by Debaditya-Som** [comment]
Here you go @AnkushFTS , submit the PR within 3 days and into the test branch. Remember to sync the branch before giving the PR

**Comment by aniketde1112** [comment]
pls assign me this
