### ISSUE TITLE
Making a home page for the netflix site 

### ISSUE THREAD

**Issue by 123shreyanvi** [rohit32999/Netflix-Sign-In-Page#23]
I'll create a home page that appears when you open it for first time.
linking the sign up page to the home page 
the home page will be a copy of original netflix page and a section of frequently asked section as mentioned in the netflix web page
I'll add some animation on scroll too .

**Comment by 123shreyanvi** [comment]
Please do assign me this

**Comment by Debaditya-Som** [comment]
Here you go @123shreyanvi , make sure you give sync your fork before giving the PR into the test branch

**Comment by 123shreyanvi** [comment]
> Here you go @123shreyanvi , make sure you give sync your fork before giving the PR into the test branch

Okay

**Comment by 123shreyanvi** [comment]
> > Here you go @123shreyanvi , make sure you give sync your fork before giving the PR into the test branch
> 
> Okay I'll do that
