### ISSUE TITLE
[UI Enhancement] the sign-in page needs some styling

### ISSUE THREAD

**Issue by anurag596** [rohit32999/Netflix-Sign-In-Page#25]

**Comment by anurag596** [comment]
@Debaditya-Som could you please add this issue under apertre tag.
i would like to work on it.

**Comment by Debaditya-Som** [comment]
Here you go @AnuragMalasi

**Comment by Debaditya-Som** [comment]
@AnuragMalasi it seems that you have unassigned yourself do you want to continue with is issue or shall I close it?
