### ISSUE TITLE
Adding background video ui

### ISSUE THREAD

**Issue by lord-cyclone100** [rohit32999/Netflix-Sign-In-Page#27]
Hello mentor and admin
I think the ui can be improved by adding the famous netflix intro video. By this I mean, when the Page is run on live server, in the background the video(5 secs long) would run and upon ending as usual the background image would be visible. During running of the video, the sign in details WOULD be visible!!

Hence, if I am allowed to add some javascript, i would love to do this
Happy coding☺️

**Comment by Debaditya-Som** [comment]
Here you go @lord-cyclone100, sync your branch before giving the PR to the test branch to avoid merge conflict :)

**Comment by lord-cyclone100** [comment]
Thanks for the oppurtunity
