### ISSUE TITLE
Adding responsiveness

### ISSUE THREAD

**Issue by rohit32999** [rohit32999/Netflix-Sign-In-Page#3]
Make the Webpage responsive for different screen sizes.

**Comment by Soumyajit-Koley** [comment]
@rohit32999 could you please assign me this , I'm interested

**Comment by itsneha15** [comment]
U can assign me this. I'll fix it .
tnxx

**Comment by YooAshu** [comment]
netflix has different ui of sign in page for mobile, i want to change it to that 
![Screenshot (53)](https://github.com/rohit32999/Netflix-Sign-In-Page/assets/95643200/ba7ac633-e2d1-4c01-a2a0-815a6dc84344)

**Comment by rohit32999** [comment]
> netflix has different ui of sign in page for mobile, i want to change it to that ![Screenshot (53)](https://private-user-images.githubusercontent.com/95643200/293605892-ba7ac633-e2d1-4c01-a2a0-815a6dc84344.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzU3ODIsIm5iZiI6MTcwNDE3NTQ4MiwicGF0aCI6Ii85NTY0MzIwMC8yOTM2MDU4OTItYmE3YWM2MzMtZTJkMS00YzAxLWEyYTAtODE1YTZkYzg0MzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA2MDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjODgxZjRiMWVlOWQ3OGE1Nzk1OTEwNGMwMmNkZDRiODdiMDg2Zjc0NzQ4YzA3ZTc4MTNhZGEzOTE2ZDk3MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dyJOBPiN--bqrkGOISX9JnE3mGjEwdxvUhk8bOZMrpg)

okay, I took a note on that.

**Comment by Sneha123-zudo** [comment]
I'm intrested in fixing this issue , please assign me this issue

**Comment by Debaditya-Som** [comment]
> netflix has different ui of sign in page for mobile, i want to change it to that ![Screenshot (53)](https://private-user-images.githubusercontent.com/95643200/293605892-ba7ac633-e2d1-4c01-a2a0-815a6dc84344.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjU3NTYsIm5iZiI6MTcwNDI2NTQ1NiwicGF0aCI6Ii85NTY0MzIwMC8yOTM2MDU4OTItYmE3YWM2MzMtZTJkMS00YzAxLWEyYTAtODE1YTZkYzg0MzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA3MDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNmE5MmMwNDA2ZjI3MDQ5Mzc1ZTdmOTk1MTlmZjFiZGU4Mzk5MzVhZmM5YzYwYWJlZDFjMTAwNzM4MTg1YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hByvCq9zvh0DJJ45awrdIAJhLspTBtDkPf5t4b8rOIM)

you can create anew issue regarding this and then we can assign you if you wish to work on it

**Comment by Debaditya-Som** [comment]
> > netflix has different ui of sign in page for mobile, i want to change it to that ![Screenshot (53)](https://private-user-images.githubusercontent.com/95643200/293605892-ba7ac633-e2d1-4c01-a2a0-815a6dc84344.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjU3NTYsIm5iZiI6MTcwNDI2NTQ1NiwicGF0aCI6Ii85NTY0MzIwMC8yOTM2MDU4OTItYmE3YWM2MzMtZTJkMS00YzAxLWEyYTAtODE1YTZkYzg0MzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA3MDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNmE5MmMwNDA2ZjI3MDQ5Mzc1ZTdmOTk1MTlmZjFiZGU4Mzk5MzVhZmM5YzYwYWJlZDFjMTAwNzM4MTg1YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hByvCq9zvh0DJJ45awrdIAJhLspTBtDkPf5t4b8rOIM)
> 
> @YooAshu  you can create anew issue regarding this and then we can assign you if you wish to work on it

**Comment by utsav306** [comment]
i want to work on it ! please assign it to me

**Comment by Debaditya-Som** [comment]
Here you go @utsav306

**Comment by utsav306** [comment]
@Debaditya-Som done !
