### ISSUE TITLE
Adding netflix logo and banner in sign-in page separately

### ISSUE THREAD

**Issue by anurag596** [rohit32999/Netflix-Sign-In-Page#37]
As of now , the netflix logo is not separate from the background of the sign-in page.
I will be adding a new background and a netflix logo appropriately so that after click logo it redirects the user to the sign-up page. and also will be adding appropriate links to (sign-up now) & (need help) button
please assign this issue to me.

**Comment by anurag596** [comment]
@Debaditya-Som could you please assign this issue to me
i would like to work on it.

**Comment by Debaditya-Som** [comment]
> @Debaditya-Som could you please assign this issue to me i would like to work on it.

okay cool
