### ISSUE TITLE
adding hover animations to the footer links ,removing the underlines add to the FAQ divs for premium look

### ISSUE THREAD

**Issue by deepbeatz** [rohit32999/Netflix-Sign-In-Page#45]
assign me this issue under apertre24
<img width="960" alt="Screenshot 2024-01-10 014019" src="https://github.com/rohit32999/Netflix-Sign-In-Page/assets/79015311/f0dfe741-180c-4e13-bf0f-930bc9defc3f">

**Comment by Debaditya-Som** [comment]
Here you go @deepbeatz

**Comment by deepbeatz** [comment]
#77 pr sent @Debaditya-Som
