### ISSUE TITLE
moblie responsiveness issue and some minor issues in styling

### ISSUE THREAD

**Issue by Rick-03** [rohit32999/Netflix-Sign-In-Page#49]
the signup page is not responsive in mobile.

before solving:
<img width="219" alt="image" src="https://github.com/rohit32999/Netflix-Sign-In-Page/assets/116449504/b0cc4c2a-e488-4e90-9113-e73d28b445b3">

after solving the issue the change:
<img width="272" alt="image" src="https://github.com/rohit32999/Netflix-Sign-In-Page/assets/116449504/7e66deb7-89d8-4bd8-be2f-3d26826e7319">

**Comment by Rick-03** [comment]
plz asssign me under apertre'24

**Comment by Debaditya-Som** [comment]
Here you go @Rick-03
