### ISSUE TITLE
[BUG] FAQ label content once expanded cannot be collapsed until any other FAQ content is expanded

### ISSUE THREAD

**Issue by itsyourap** [rohit32999/Netflix-Sign-In-Page#57]
Currently, the Frequently Asked Questions section has labels, which when clicked, expands its contents but clicking the label again won't collapse the contents back.
The only way to collapse a FAQ content is by expanding another FAQ content.

The proper implementation should be, when a label is clicked and its contents expanded, another click should collapse its contents.

I would like to fix this issue.

Please assign me under Apertre '24

**Comment by itsyourap** [comment]
@Debaditya-Som Please assign me this issue under Apertre '24

**Comment by Debaditya-Som** [comment]
Here you go :)
