### ISSUE TITLE
[BUG] Fix background image while see Netflix logo

### ISSUE THREAD

**Issue by Geeks-Arpan** [rohit32999/Netflix-Sign-In-Page#6]
![Netflix](https://github.com/rohit32999/Netflix-Sign-In-Page/assets/99377659/aa1e4f6c-cafb-4a36-9639-19cb08b8236e)

**Comment by itsneha15** [comment]
Can i fix it? Im interested tho ! Tnxx

**Comment by Debaditya-Som** [comment]
> Can i fix it? Im interested tho ! Tnxx

We appreciate your will to contribute to this issue, but it has been created by @Geeks-Arpan  and he is willing to contribute to it. So, we would suggest you to look for another issue or create an issue of your own. Incase @Geeks-Arpan  is not willing or is unable to work on this issue we'll assign you :)

**Comment by Debaditya-Som** [comment]
Thanks @Geeks-Arpan for opening this issue, would you like to work on it?

**Comment by Debaditya-Som** [comment]
, @Geeks-Arpan haven't responded in a while so @nsrs-78 do you want to take on this issue?

**Comment by itsneha15** [comment]
Yup sure

**Comment by rko0211** [comment]
Kindly assign me this task if required..
