### ISSUE TITLE
fixing sign-in box

### ISSUE THREAD

**Issue by anurag596** [rohit32999/Netflix-Sign-In-Page#65]
the sign-in box does't look good
so i'll be fixing it
![Screenshot 2024-01-13 011400](https://github.com/rohit32999/Netflix-Sign-In-Page/assets/125523667/2ac8337e-47d9-4829-964d-42a69fcfee71)

**Comment by AnuragMalasi** [comment]
@Debaditya-Som please assign this issue to me
thanks :)

**Comment by anurag596** [comment]
@Debaditya-Som please assign this issue to me 
thanks :)

**Comment by Debaditya-Som** [comment]
It seems to be an easy issue you can do it under the same issue #71
