### ISSUE TITLE
Add new feature : API boxes

### ISSUE THREAD

**Issue by apu52** [rohit32999/Netflix-Sign-In-Page#68]
**Describe the feature you are requesting**

Hello Sir,
I want to add some cool badges in this repo like
- open issues
- contributor
- open PR
- last commites
this type of cool API badges
It will be very helpful to showcase the stats of your Repo as well as will attract more contributors.
**Additional context(if any)**

![image](https://github.com/rohit32999/Netflix-Sign-In-Page/assets/114172928/a96dcd44-4775-461e-90c9-615598a724fa)

***Are you contributing under any open-source program ?***

APERTRE'24

**Comment by apu52** [comment]
@rohit32999 Please assign me this issue under APERTRE'24

**Comment by apu52** [comment]
@Debaditya-Som Please assign me this issue

**Comment by Debaditya-Som** [comment]
Here you go :)
