### ISSUE TITLE
Instead of forgot password it would be need help

### ISSUE THREAD

**Issue by aniketde1112** [rohit32999/Netflix-Sign-In-Page#7]
problem:- The actual sign in page of netflix has need help option than that of Forgot password
solution:- Change it for the same

**Comment by Debaditya-Som** [comment]
Hi @aniketde1112 , thanks for opening this issue and showing your interest in working on our project :)

**Comment by Debaditya-Som** [comment]
Thanks for pointing out this issue, but it seems that it has already been taken care of so you may work on a different issue #16 .
