### ISSUE TITLE
Add the footer section

### ISSUE THREAD

**Issue by IndraniSom** [rohit32999/Netflix-Sign-In-Page#8]
I want to make the footer section for the sign in page

**Comment by rko0211** [comment]
Hello i want to contribute in this issue under apertre24 kindly assign me this task.

**Comment by anurag596** [comment]
i would like to create footer for this sign-in page.
please assign this issue to me
thanks

**Comment by Debaditya-Som** [comment]
Here you go @IndraniSom

**Comment by guddubasu** [comment]
I want to work on the same issue

**Comment by Debaditya-Som** [comment]
@IndraniSom how are you progressing with this issue?

**Comment by rko0211** [comment]
Hey i want to work on this

**Comment by anurag596** [comment]
@Debaditya-Som the time given for hard issue was 3 days. 
Since the time is already exceeded for previous assignee could you please assign this issue to me

**Comment by Debaditya-Som** [comment]
@AnuragMalasi yep you are right, but for hard problem the time given is 5 days and also chronologically @rko0211 asked first so i'll need to assign him

**Comment by AnuragMalasi** [comment]
@Debaditya-Som please assign this to me
