### ISSUE TITLE
Frequently asked question tab is not working properly in signin.html

### ISSUE THREAD

**Issue by rko0211** [rohit32999/Netflix-Sign-In-Page#86]
![Screenshot from 2024-01-18 16-41-25](https://github.com/rohit32999/Netflix-Sign-In-Page/assets/97402824/6852d546-1135-4b8d-ba6b-5da413fbf6cf)

It is not closed once click on any queries..

**Comment by itsyourap** [comment]
It was fixed in #57 with #72 

Please update your branch
