### ISSUE TITLE
[FEATURE] [UI/UX] Logo of the website is required

### ISSUE THREAD

**Issue by Debaditya-Som** [rohit32999/Netflix-Sign-In-Page#9]
The current state of the website is missing the Netflix logo. So, the logo needs to be added to the website,

**Comment by AnitSarkar123** [comment]
Assign me under Apertre'24

**Comment by Debaditya-Som** [comment]
> Assign me under Apertre'24

Thanks for showing your interest in our project, we'll start assigning the issues from 3rd Jan

**Comment by anurag596** [comment]
> The current state of the website is missing the amazon logo. So, the logo needs to be added to the website,

i think its Netflix logo not Amazon logo
and i saw the logo on the sign-in page, it's there!!!

**Comment by Debaditya-Som** [comment]
> > The current state of the website is missing the amazon logo. So, the logo needs to be added to the website,
> 
> i think its Netflix logo not Amazon logo
> and i saw the logo on the sign-in page, it's there!!!

Yes it'll be Netflix logo...my bad..am working on another project so it's just getting mixed although.. nvm

**Comment by Sneha123-zudo** [comment]
I'm intrested in fixing this issue , please assign me this issue

**Comment by Debaditya-Som** [comment]
@Sneha123-zudo there you go
